[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
avenir = "PjLEXWGmgCA78MTaK9fN1k4muUiis2gdkUkrXRHRUkN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun run tests/"
